//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace todosServicos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_servicosEntities : DbContext
    {
        public db_servicosEntities()
            : base("name=db_servicosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Cidade> TB_Cidade { get; set; }
        public virtual DbSet<TB_Estado> TB_Estado { get; set; }
        public virtual DbSet<TB_LocalizacaoUsuario> TB_LocalizacaoUsuario { get; set; }
        public virtual DbSet<TB_PerfilUsuario> TB_PerfilUsuario { get; set; }
        public virtual DbSet<TB_Servico> TB_Servico { get; set; }
        public virtual DbSet<TB_ServicoUsuario> TB_ServicoUsuario { get; set; }
        public virtual DbSet<TB_SolicitacaoServico> TB_SolicitacaoServico { get; set; }
        public virtual DbSet<TB_SolicitacaoStatus> TB_SolicitacaoStatus { get; set; }
        public virtual DbSet<TB_Usuario> TB_Usuario { get; set; }
        public virtual DbSet<TB_Solicitacao> TB_Solicitacao { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> STP_INS_Usuario(string login, string senha, Nullable<bool> flAtivo)
        {
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            var senhaParameter = senha != null ?
                new ObjectParameter("senha", senha) :
                new ObjectParameter("senha", typeof(string));
    
            var flAtivoParameter = flAtivo.HasValue ?
                new ObjectParameter("flAtivo", flAtivo) :
                new ObjectParameter("flAtivo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("STP_INS_Usuario", loginParameter, senhaParameter, flAtivoParameter);
        }
    
        public virtual ObjectResult<STP_LST_BuscarServicoPorLocalizacao_Result> STP_LST_BuscarServicoPorLocalizacao(Nullable<double> latitude, Nullable<double> longitude, Nullable<int> idServico)
        {
            var latitudeParameter = latitude.HasValue ?
                new ObjectParameter("latitude", latitude) :
                new ObjectParameter("latitude", typeof(double));
    
            var longitudeParameter = longitude.HasValue ?
                new ObjectParameter("longitude", longitude) :
                new ObjectParameter("longitude", typeof(double));
    
            var idServicoParameter = idServico.HasValue ?
                new ObjectParameter("idServico", idServico) :
                new ObjectParameter("idServico", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_LST_BuscarServicoPorLocalizacao_Result>("STP_LST_BuscarServicoPorLocalizacao", latitudeParameter, longitudeParameter, idServicoParameter);
        }
    }
}
