//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace todosServicos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LocalizacaoUsuario
    {
        public int idLocalizacao { get; set; }
        public int idUsuario { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public Nullable<System.DateTime> dataUltimaAtualzacao { get; set; }
        public Nullable<double> distancia { get; set; }
    
        public virtual TB_Usuario TB_Usuario { get; set; }
    }
}
