//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace todosServicos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PerfilUsuario
    {
        public int idPerfilUsuario { get; set; }
        public int idUsuario { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public string email { get; set; }
        public string endereco { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string cep { get; set; }
        public int idEstado { get; set; }
        public int idCidade { get; set; }
        public string tipoPerfil { get; set; }
    
        public virtual TB_Cidade TB_Cidade { get; set; }
        public virtual TB_Estado TB_Estado { get; set; }
        public virtual TB_Usuario TB_Usuario { get; set; }
    }
}
