//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace todosServicos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Servico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Servico()
        {
            this.TB_ServicoUsuario = new HashSet<TB_ServicoUsuario>();
            this.TB_SolicitacaoServico = new HashSet<TB_SolicitacaoServico>();
        }
    
        public int idServico { get; set; }
        public string descricao { get; set; }
        public Nullable<bool> flAtivo { get; set; }
        public string Imagem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ServicoUsuario> TB_ServicoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SolicitacaoServico> TB_SolicitacaoServico { get; set; }
    }
}
