//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace todosServicos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Solicitacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Solicitacao()
        {
            this.TB_SolicitacaoServico = new HashSet<TB_SolicitacaoServico>();
        }
    
        public int idSolicitacao { get; set; }
        public int idStatus { get; set; }
        public Nullable<System.DateTime> dtCricao { get; set; }
        public Nullable<int> idUsuarioOrigem { get; set; }
        public Nullable<int> idUsuarioDestino { get; set; }
        public Nullable<System.DateTime> dtRetirada { get; set; }
        public Nullable<System.DateTime> dtRecebidoCentral { get; set; }
        public Nullable<System.DateTime> dtValidacao { get; set; }
        public Nullable<System.DateTime> dtEnvioDestino { get; set; }
        public Nullable<System.DateTime> dtEntregue { get; set; }
        public Nullable<System.DateTime> dtDevolucao { get; set; }
        public Nullable<int> idDevolucaoMotivo { get; set; }
        public string obsMotivoDevolucao { get; set; }
        public string recebidoPor { get; set; }
    
        public virtual TB_Solicitacao TB_Solicitacao11 { get; set; }
        public virtual TB_Solicitacao TB_Solicitacao2 { get; set; }
        public virtual TB_SolicitacaoStatus TB_SolicitacaoStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SolicitacaoServico> TB_SolicitacaoServico { get; set; }
    }
}
