//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace todosServicos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SolicitacaoServico
    {
        public int idSolicitacaoServico { get; set; }
        public int IdSolicitacao { get; set; }
        public int idServico { get; set; }
        public Nullable<int> qtde { get; set; }
    
        public virtual TB_Servico TB_Servico { get; set; }
        public virtual TB_Solicitacao TB_Solicitacao { get; set; }
    }
}
