//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace todosServicos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Usuario()
        {
            this.TB_LocalizacaoUsuario = new HashSet<TB_LocalizacaoUsuario>();
            this.TB_PerfilUsuario = new HashSet<TB_PerfilUsuario>();
            this.TB_ServicoUsuario = new HashSet<TB_ServicoUsuario>();
        }
    
        public int idUsuario { get; set; }
        public string Login { get; set; }
        public byte[] Senha { get; set; }
        public bool flAtivo { get; set; }
        public System.DateTime dtCriacao { get; set; }
        public System.DateTime dtAtivacao { get; set; }
        public Nullable<System.DateTime> dtInativacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_LocalizacaoUsuario> TB_LocalizacaoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PerfilUsuario> TB_PerfilUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ServicoUsuario> TB_ServicoUsuario { get; set; }
    }
}
